site_name: Tiki
site_description: Boli's notes and drafts
site_author: Boli Tao
site_url: https://wiki.bolitao.xyz
copyright: '&copy; 2020 bolitao'
theme:
  name: material
  # language: 'zh'
  # icon:
  #   logo: material/library
  # favicon: images/favicon.png
  palette:
    # scheme: slate
    primary: 'deep purple'
    accent: 'deep purple'
  shortcuts:
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  font:
    text: Noto Serif SC
    code: Jetbrains Mono
  # features:
  #   - tabs: true
  #   - navigation.tabs
plugins:
  - search
      # lang: 'en', 'ru'
extra:
  social:
    - icon: fontawesome/solid/home
      link: https://bolitao.xyz
  search:
    language: 'en, ja'
# google_analytics:
#   - UA-XXXXXXXX-X
#   - auto
# nav:
